### ISSUE TITLE
Collision Detection Issue

### ISSUE THREAD

**Issue by vanityx** [vanityx/AlienGame#4]
It does not always register as "hit" when the slime collides with the ice cream

**Comment by almeister** [comment]
You might want to consider using PyGame’s built-in sprite collision handling, especially if you wish to have multiple ice creams on screen.

http://programarcadegames.com/index.php?chapter=introduction_to_sprites

https://www.pygame.org/docs/ref/sprite.html#pygame.sprite.spritecollide
